### ISSUE TITLE
Faire les cartes candidateForAJob

### ISSUE THREAD

**Issue by SateaMall** [tony-nguyen1/Inteco#4]

**Comment by tony-nguyen1** [comment]
![image](https://github.com/tony-nguyen1/Inteco/assets/47113757/2ea73109-be99-4b4e-a4bc-fa9b541c6401)

**Comment by tony-nguyen1** [comment]
fr.umontpellier.etu.inteco.Enterprise.fragements.candidateForAJob.CandidateProfilActivity.java
 R.layout.activity_candidate_profil

**Comment by SateaMall** [comment]
Done..
J'ai pas rajouté les fonctionnalité pour le cv car il me semble qu'on aurai pas le temps pour le faire 
Dit moi si tu veux que je les fasse
